### PR TITLE
added automatic parsing of json for TR and FA

### LINKED ISSUE #27: MTsat calculation: use JSON values instead of hard-coded ones
In [this line of code](https://github.com/sct-pipeline/spine-generic/blob/master/processing/process_data.sh#L167), TR and flip angle are currently hard-coded, but ultimately those values should be extracted from the json file. 

This could be done via bash or a python reader. Either way is fine.

### PR DESCRIPTION
**Pull request by Nicolas-Pinon**
Didn't have time to test the whole script yet, not really elegant but should do the trick

Fixes #27

### CODE REVIEW

**Comment by jcohenadad** [comment]
thanks for the quick implementation 👍 i will test asap

**Comment by jcohenadad** [comment]
@Nicolas-Pinon your code doesn't work-- issue if more than 2 numbers-- could you pls find a workaround? thx

**Comment by Nicolas-Pinon** [comment]
Fixed the parsing, should work now (+ solution more elegant), doing the testing now on abbey

**Comment by jcohenadad** [comment]
> Fixed the parsing, should work now (+ solution more elegant), doing the testing now on abbey

Awesome 👍 Let me know when you finish the testing so we can merge. Thanks!

**Comment by Nicolas-Pinon** [comment]
Everything ran just fine on my end ! :)

**Comment by jcohenadad** [comment]
Awesome! I'll clean up a bit (make function to avoid duplication) and merge. Thanks!

**Pull request merged**
