### PR TITLE
fix site names (issues #47)

### PR DESCRIPTION
**Pull request by valosekj**
Proposed solution for #47

### CODE REVIEW

**Comment by alexfoias** [comment]
do we only need to change the following ?

- brno → brnoUH
- brnoPrisma → brnoCEITEC

**Comment by jcohenadad** [comment]
> do we only need to change the following ?
> 
> * brno → brnoUH
> * brnoPrisma → brnoCEITEC

yes i think so

**Comment by alexfoias** [comment]
Okay. Are we only changing the info in the column `institution_id` or do we need to rename the subjects as well ?

**Comment by jcohenadad** [comment]
> Okay. Are we only changing the info in the column `institution_id` or do we need to rename the subjects as well ?

let's go with the clean approach: change subject id as well

**Comment by alexfoias** [comment]
I rechecked the names that I suggested on top with regard to the ones [here](https://github.com/sct-pipeline/spine-generic/issues/47#issue-446711620). 
The correct naming convention should be this one:
- brno → UHBrno
- brnoPrisma → CEITECBrno

@jcohenadad Could you please confirm before I go ahead in propagating the changes ? thanks.

**Comment by jcohenadad** [comment]
> I rechecked the names that I suggested on top with regard to the ones [here](https://github.com/sct-pipeline/spine-generic/issues/47#issue-446711620).
> The correct naming convention should be this one:
> 
> * brno → UHBrno
> * brnoPrisma → CEITECBrno
> 
> @jcohenadad Could you please confirm before I go ahead in propagating the changes ? thanks.

@alexfoias what convention are you referring to?  i'm looking at the list of sites [here](https://openneuro.org/datasets/ds001919/versions/1.0.5), and it seems that the camelCase (with first letter small) is the adopted convention. Moreover, cases where a city has more than one center (e.g. oxford), the city is first, then the center. Which means that we should probably have something like this: `brnoUhb` and `brnoCeitec`. @valosekj are you OK with this?

**Comment by valosekj** [comment]
@jcohenadad yes, it looks fine for me. Maybe, better than `brnoUhb` could be `brnoUh` (without b at the end). 'brnoUh' stands for University Hospital Brno, so it is not probably necessary to include the last b (meaning first letter from Brno city) because Brno (=city) is already included in the name. I only quickly ask colleagues from there for confirmation. I will let know.
`brnoCeitec` is fine, it means Central European Institute of Technology (CEITEC) Brno.

**Comment by jcohenadad** [comment]
> @jcohenadad yes, it looks fine for me. Maybe, better than `brnoUhb` could be `brnoUh` (without b at the end). 'brnoUh' stands for University Hospital Brno, so it is not probably necessary to include the last b (meaning first letter from Brno city) because Brno (=city) is already included in the name. I only quickly ask colleagues from there for confirmation. I will let know.
> `brnoCeitec` is fine, it means Central European Institute of Technology (CEITEC) Brno.

yes i got it about the duplicated b, but sometimes institution names are immutable (e.g. we write "university of oxford, oxford, uk" not "university of, oxford, uk").

**Comment by valosekj** [comment]
@jcohenadad So, after discussion with colleagues, `brnoUhb` and `brnoCeitec` is fine for us. Thank you 👍

**Comment by alexfoias** [comment]
We have changed the names in 1.0.7. We can close this PR.

**Comment by jcohenadad** [comment]
change implemented in this release: https://github.com/sct-pipeline/spine-generic/releases/tag/v1.1

**Pull request closed without merging**
